#!/bin/sh
# Переустановка маршрутов Wi-Fi при подключении и продлении аренды.
IFACE="$1"; ACTION="$2"
case "$IFACE" in
    wlan[0-9]*|swlan0|wlp1s0) ;;
    *) exit 0 ;;
esac
case "$ACTION" in
    up|dhcp4-change) /usr/lib/adaptation-samsung-gts7l/wlan-routes-fix ;;
esac
exit 0
